### ISSUE TITLE
Hallo  Kann ich die Apps wieder löschen nachdem ich meine Apps installiert habe oder muss ich ioniqroot immer drauf lassen.

### ISSUE THREAD

**Issue by andre1078** [g4rb4g3/IoniqRoot#1]
Hi

Can I delete the apps after I have installed my apps or do I always have to leave ioniqroot on them.

(Hallo

Kann ich die Apps wieder löschen nachdem ich meine Apps installiert habe oder muss ich ioniqroot immer drauf lassen.)

**Comment by g4rb4g3** [comment]
You can uninstall it.
