### ISSUE TITLE
Crashes on firmware 191209 K2

### ISSUE THREAD

**Issue by slytimer** [g4rb4g3/IoniqRoot#4]
Hi. After install app and run, any actions has closed app. Kia optima 19. What debug log should I get for determine reason.

**Comment by g4rb4g3** [comment]
Install SDK Platform Tools
https://developer.android.com/studio/releases/platform-tools
Connect your computer and your car to the same WiFi.
Open a terminal and connect to your cars wifi up using:
`adb connect CARIP:5555`
Next run logcat
`adb logcat > log.txt`
Start the app and let it crash. Kill logcat by pressing `<Strg>+C`.
Open the log.txt in some Editor. Look for lines containing some exception.

**Comment by slytimer** [comment]
[log2.txt](https://github.com/g4rb4g3/IoniqRoot/files/4840954/log2.txt)
nope, just closing the app when i press "restore stock applications" or "reboot"
maybe this section?
```
ContextImpl(  504): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1057 android.content.ContextWrapper.sendBroadcast:338 com.lge.ivi.coreserver.dg.handleMessage:-1 android.os.Handler.dispatchMessage:99 android.os.Looper.loop:137 

ContextImpl(  504): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1057 android.content.ContextWrapper.sendBroadcast:338 com.lge.ivi.app.Osd.handleShow:596 com.lge.ivi.app.Osd.setStateInternal:695 com.lge.ivi.app.Osd.access$900:33 `
```

**Comment by g4rb4g3** [comment]
Sorry there is nothing in the log you provided.
This has only been tested with the Ioniq. I know it's working on the Kia Niro PHEV too.
Maybe there is some issue with the native lib (extmedia_jni).
Only way to find out is to grab the com.lge.ivi.jar & com.lge.ivi.odex files from /system/framework, deodex them, use dex2jar and build IoniqRoot on your own.
Debugging it should give you an idea why it crashes on your head unit.

**Comment by abogasem81** [comment]
Can any one help me to go back from this screen on kia sportage 2018 korea
After i went to engineering mood 
Then android update options 
I chose update by usp
Then its like this from 1 week 
![Uploading 20210315_105801.jpg…]()
