### ISSUE TITLE
200401 firmware support

### ISSUE THREAD

**Issue by Anonym-tsk** [g4rb4g3/IoniqRoot#5]
Please add support of 200401 firmware

**Comment by g4rb4g3** [comment]
Since this version is not available for the Ioniq (yet?) there is nothing I can do.

**Comment by Anonym-tsk** [comment]
You can remove version check from code and make experimental build. Beta version for testers.

**Comment by g4rb4g3** [comment]
This won't help because the stock apps have to match the firmware version. The 191209 files won't work on any other firmware.
