### ISSUE TITLE
libvitnavijni_45ECN.so

### ISSUE THREAD

**Issue by upgreydd** [g4rb4g3/IoniqRoot#6]
Hey mate,
If you're not continuing your work with ionic, can you please upload libvitnavijni_45ECN.so source code to your github? I'll appreciate it. I'm trying to do the same injection but for GEN4 Kia/Hyundai unit - would be great to have some template and start point.

**Comment by g4rb4g3** [comment]
I don't have that code anymore. It is just a simple c library that launches an apk when it gets loaded.
